# Change these first
owner: bobbyorg # Your GitHub organization or username, where this repository lives
repo: upptime_org # The name of this repository

sites:
  - name: ORG Website
    url: https://www.orientalremediesgroup.com/
  - name: VD Login Page
    url: https://hub.vaultdragon.com/login
  - name: SleekFlow
    url: https://app.sleekflow.io/
  - name: SimplyBook
    url: https://orientalremediesgroup.secure.simplybook.asia/v2/index/index
  - name: JE CCTV
    url: ${{secrets.JE_CCTV}}
    port: ${{secrets.JE_PORT}}
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

#  - name: Vault Dragon API Login
#    url: ${{ secrets.VD_URL }}
#    check: "http-body-match"
    # From your headers, the success code is 201 Created.
    # Check the "Response" tab in your browser's developer tools for the
    # actual JSON body that is returned on success.
    # Update the text below to match a key from that JSON, like "token" or "id".
#    __dangerous__body_down_if_text_missing: '"token"'
#    __dangerous__curl_args:
#      - "--request"
#      - "POST"
      # Add all the headers your browser sends to look like a legitimate request
#      - "--header"
#      - "Content-Type: application/json;charset=UTF-8"
#      - "--header"
#      - "Accept: application/json"
#      - "--header"
#      - "Origin: https://hub.vaultdragon.com" # <-- VERY LIKELY REQUIRED
#      - "--header"
#      - "Referer: https://hub.vaultdragon.com/" # <-- VERY LIKELY REQUIRED
#      - "--header"
#      - "x-client-tz: Asia/Singapore"
#      - "--header"
#      - "x-org: orgtcm" # <-- This custom header might be required.
      # Set the User-Agent to match a real browser
 #     - "--user-agent"
 #     - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
 #     - "--location"
 #     - "--fail"
 #     - "--data"
      # The JSON data payload
#      - |
#        {
#          "orgCode": "${{ secrets.VD_CODE }}",
#          "email": "${{ secrets.VD_SERVICEUSER }}",
#          "password": "${{ secrets.VD_PW }}"
#        }
    #orgCode: $VD_CODE
  #  email: $VD_SERVICEUSER
  #  password: $VD_PW

  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: www.orientalremediesgroup.com
  baseUrl: /upptime_org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
